source 'https://rubygems.org'

gem 'rake'
gem 'redpotion'
gem "ProMotion-forms"
gem "cdq" # Core Data 
gem "afmotion" # Networking
gem "motion-cocoapods" # Pods

# gem "ProMotion-push", "~> 0.2" # Push Notifications
# gem "ProMotion-map", "~> 0.3"  # PM::MapScreen

# For beta distribution a exception reporting
#gem "motion-hockeyapp" 

# Useful tools 
#gem "bubble-wrap" 
